import Link from "next/link"
import "./globals.css"
import Image from "next/image"
// Import fontawesome
import "@fortawesome/fontawesome-svg-core/styles.css"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="corporate">
      <body>
        {/* buat area header */}
        <header>
          {/* buat area image */}
          {/*<img src="../images/logo.png" alt="LOGO UTI" />*/}
          <Image src={"/images/logo.png"} alt="LOGO UTI" width={320} height={60} priority></Image>

          {/* buat area menu */}
          <nav className="text-center mt-5 flex justify-center">
            <Link href={"/"}className="bg-purple-500 shadow-xl rounded-full text-white px-5 py-2.5 hover:bg-purple-700 mr-2 w-64">Data Mahasiswa</Link>
            <Link href={"/"}className="bg-purple-500 shadow-xl rounded-full text-white px-5 py-2.5 hover:bg-purple-700 ml-2 w-64">Log Data Mahasiswa</Link>
          </nav>
        </header>
        {/* buat area content */}
        <section className="m-5">
        {children}
        </section>

        {/* buat area footer */}
        <footer className="text-color1 bg-color2 py-5px text-center flex justify-center">
          Copyright &copy; 2024 - Aqgit Ariya Kusuma
        </footer>
      </body>
    </html>
  )
}
